name: Daily Trading Strategy

on:
  schedule:
    # Runs at 00:00 UTC every day (adjust this time as needed)
    - cron: '0 0 * * *'
  workflow_dispatch:  # Allows manual trigger of the workflow

jobs:
  run-strategy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yfinance pandas matplotlib alpaca-trade-api

    - name: Run trading strategy
      env:
        ALPACA_API_KEY: ${{ secrets.ALPACA_API_KEY }}
        ALPACA_API_SECRET: ${{ secrets.ALPACA_API_SECRET }}
      run: |
        python trading_strategy.py